[deploy]
bucket = 'cruddur-cfn-templates'
region = 'ca-central-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://odfd.net'
EnvBackendUrl = 'https://api.odfd.net'
DDBMessageTable = 'CrdDdb-DynamoDBTable-RWAVLMGBPA47'