[deploy]
bucket = 'cruddur-cfn-templates'
region = 'ca-central-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'oflorez1381/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "cruddur-code-pipeline-artifacts"